name: 'Cloudinary Upload Images'
author: '@KMOZ000'
description: 'Upload your medias with Cloudinary Upload Github Action to Cloudinary SaaS solution.'
branding:
  icon: arrow-up-circle
  color: purple
inputs:
  cloud-name:
    description: 'Cloudinary account name'
    required: false
    default: '<name>'
  api-key:
    description: 'Cloudinary API Key'
    required: false
    default: '<api-key>'
  api-secret:
    description: 'Cloudinary API Secret Key'
    required: false
    default: '<api-secret>'
  file:
    description: 'Image path to upload'
    required: false
    default: ""
  file:
    description: 'Pattern or array of file path to upload'
    required: false
    default: ""
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node20'
  main: 'dist/index.js'
